listen=YES
listen_ipv6=NO

# Pas d’anonyme
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

# Chroot dans le volume partagé (monté /srv/sites)
chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/srv/sites

# Liste blanche d’utilisateurs autorisés
userlist_enable=YES
userlist_file=/etc/vsftpd/user_list
userlist_deny=NO

# Mode passif
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110

# Divers
secure_chroot_dir=/var/run/vsftpd/empty
seccomp_sandbox=NO
utf8_filesystem=YES

max_clients=25        # connexions simultanées
max_per_ip=3          # connexions par IP
accept_timeout=30
connect_timeout=30
